"""empty message

Revision ID: 6fa19e201ce5
Revises: 2355e2fb1c78
Create Date: 2018-11-21 16:41:13.275503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa19e201ce5'
down_revision = '2355e2fb1c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
