"""empty message

Revision ID: 7fdf56737fd0
Revises: 35fe8e61b6f5
Create Date: 2018-10-01 21:14:44.161926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdf56737fd0'
down_revision = '35fe8e61b6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'medical', sa.Column('visit_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'medical', 'visit', ['visit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical', type_='foreignkey')
    op.drop_column(u'medical', 'visit_id')
    op.drop_table('visit')
    # ### end Alembic commands ###
