"""empty message

Revision ID: f7579445f234
Revises: 2feafb94b028
Create Date: 2018-10-15 14:33:32.515121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7579445f234'
down_revision = '2feafb94b028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'metrics', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'metrics', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_column(u'metrics', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
